-- 1. Create the daily_logs table
CREATE TABLE public.daily_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  log_date DATE NOT NULL,

  -- General Info
  time_awake TIME,

  -- Morning Routine
  coffee BOOLEAN,
  morning_walk BOOLEAN,

  -- Meals & Health
  breakfast BOOLEAN,
  green_tea BOOLEAN,
  alcohol BOOLEAN,
  smoke BOOLEAN,
  soda BOOLEAN,
  chocolate BOOLEAN,

  -- Intake
  dabs_count SMALLINT CHECK (dabs_count >= 0 AND dabs_count <= 6),
  water_bottles_count SMALLINT CHECK (water_bottles_count >= 1 AND water_bottles_count <= 10),
  pages_read_count INTEGER CHECK (pages_read_count >= 0),

  -- Night Routine
  brushed_teeth_night BOOLEAN,
  washed_face_night BOOLEAN,

  -- Screen Habits
  netflix_in_bed BOOLEAN,
  phone_on_wake BOOLEAN,

  -- Fitness
  workout TEXT[],

  -- Wellness
  relaxed_today BOOLEAN,
  day_rating TEXT,

  -- Metrics
  weight_lbs NUMERIC,
  calories INTEGER,
  bed_time TIME,
  dream TEXT,
  latest_hype TEXT,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Make sure each user has only one log per day
  UNIQUE (user_id, log_date)
);

-- 2. Add comments to describe the columns
COMMENT ON TABLE public.daily_logs IS 'Stores daily log entries for users.';
COMMENT ON COLUMN public.daily_logs.phone_on_wake IS 'Did I use my phone for Social Media within 30 mins of waking up?';

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.daily_logs ENABLE ROW LEVEL SECURITY;

-- 4. Create policies for RLS
-- Users can insert their own logs
CREATE POLICY "Users can insert their own daily_logs" ON public.daily_logs
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Users can view their own logs
CREATE POLICY "Users can view their own daily_logs" ON public.daily_logs
  FOR SELECT USING (auth.uid() = user_id);

-- Users can update their own logs
CREATE POLICY "Users can update their own daily_logs" ON public.daily_logs
  FOR UPDATE USING (auth.uid() = user_id);

-- Users can delete their own logs
CREATE POLICY "Users can delete their own daily_logs" ON public.daily_logs
  FOR DELETE USING (auth.uid() = user_id);
